name: Unix

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      # Increase this value to reset cache
      env: {CACHE_NUMBER: 0}
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ matrix.python-version }}

    - uses: conda-incubator/setup-miniconda@v2
      name: Setup conda
      with:
        auto-update-conda: true
        activate-environment: testing
        auto-activate-base: false
        channels: conda-forge,defaults
        channel-priority: true

    - shell: bash -eo pipefail -l {0}
      name: Install dependencies
      run: |
        conda install -y -c conda-forge mamba
        mamba env create --file conda.yml
        mamba install -y -c conda-forge pyflakes

    - shell: bash -eo pipefail -l {0}
      name: Install
      run: |
        python3 -m pip install -v .

    - shell: bash -eo pipefail -l {0}
      name: pyflakes
      run: python -m pyflakes lasy

    - shell: bash -eo pipefail -l {0}
      name: test example
      run: |
        cd examples
        python3 test.py
