name: Unix

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-unix
  cancel-in-progress: true

jobs:
  unittest:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r tests/requirements.txt

    - name: Install
      run: python -m pip install -v .

    - name: Run Unit Tests
      run: python -m pytest tests/

  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python3 -m pip install -U pyflakes
    - name: pyflakes
      run: python -m pyflakes lasy
