name: Unix

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-unix
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      # Increase this value to reset cache
      env: {CACHE_NUMBER: 0}
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ matrix.python-version }}

    - uses: conda-incubator/setup-miniconda@v2
      name: Setup conda
      with:
        auto-update-conda: true
        activate-environment: testing
        auto-activate-base: false
        channels: conda-forge,defaults
        channel-priority: true

    - shell: bash -eo pipefail -l {0}
      name: Install dependencies
      run: |
        conda install -y -c conda-forge mamba
        mamba install -y -c conda-forge python=${{ matrix.python-version }} openpmd-viewer pyflakes pytest
        mamba env update --name testing --file conda.yml

    - shell: bash -eo pipefail -l {0}
      name: Install
      run: python -m pip install -v .

    - shell: bash -eo pipefail -l {0}
      name: pyflakes
      run: python -m pyflakes lasy

    - shell: bash -eo pipefail -l {0}
      name: Run Unit Tests
      run: python -m pytest tests/

    - shell: bash -eo pipefail -l {0}
      name: Run Examples
      run: |
        cd examples
        python test.py
